trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300'

- script: dotnet restore
  displayName: 'dotnet restore'

- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'dotnet build'

- script: dotnet pack --output $(build.artifactStagingDirectory) --configuration $(buildConfiguration) --no-restore
  displayName: 'dotnet pack'
