trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'release'

steps:
- script: dotnet restore
  displayName: 'dotnet restore'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build'

- script: dotnet pack --output $(build.artifactStagingDirectory) --no-build
  displayName: 'dotnet pack'
